#!/usr/bin/env bun
// Offline replay bench for pi-jev triage. See bench/replay/RESULTS.md for output.
//   bun run bench/replay/cli.ts <extract|judge|score|report>
//       [--judge vercel|typesafe|local|mock] [--limit N] [--sample stratified] [--sample-n N]
//       [--timeout-ms N] [--dry-run] [--yes]
// --timeout-ms overrides PI_JEV_TIMEOUT_MS (default 15000). PI_JEV_QUESTION_SET (sharpened|winnow) picks the triage question.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { OUT_ROOT } from "./corpus.ts";
import { runExtract, FEATURES } from "./extract.ts";
import { runJudge, scanCases, stratifiedPick, usd, judgedPath } from "./judge.ts";
import { comparisonTable, runScore, toMarkdown } from "./score.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

function parse(argv: string[]) {
  const cmd = argv[0];
  const o: Record<string, string | boolean> = {};
  for (let i = 1; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) continue;
    const k = a.slice(2);
    const v = argv[i + 1];
    if (v && !v.startsWith("--")) { o[k] = v; i++; } else o[k] = true;
  }
  return { cmd, o };
}

async function main() {
  const { cmd, o } = parse(process.argv.slice(2));
  const judge = o.judge as string;
  const JUDGES = ["vercel", "typesafe", "local", "mock"];
  if ((cmd === "judge" || cmd === "score") && !JUDGES.includes(judge)) throw new Error(`--judge must be one of ${JUDGES.join(", ")}`);

  if (cmd === "extract") {
    const t0 = Date.now();
    const st = await runExtract({ limit: o.limit ? Number(o.limit) : undefined });
    const secs = (Date.now() - t0) / 1000;
    console.log(`sessions=${st.sessions} turns=${st.turns} in ${secs.toFixed(0)}s`);
    console.log(`triage: cases=${st.triage.cases.toLocaleString()} blocks=${st.triage.blocks.toLocaleString()} needed=${st.triage.needed.toLocaleString()} (${(100 * st.triage.needed / (st.triage.blocks || 1)).toFixed(1)}%) resultBytes=${(st.triage.resultBytes / 1e6).toFixed(0)}MB truncated=${st.triage.truncated}`);
    for (const [f, b] of Object.entries(st.caseBytes)) console.log(`  ${f}.jsonl ${(b / 1e6).toFixed(0)} MB`);
    mkdirSync(join(OUT_ROOT, "scores"), { recursive: true });
    writeFileSync(join(OUT_ROOT, "scores", "extract.json"), JSON.stringify({ ...st, secs, at: new Date().toISOString() }, null, 2));
    return;
  }

  if (cmd === "judge") {
    for (const f of FEATURES) {
      if (o["dry-run"]) {
        const metas = await scanCases(f);
        const all = metas.reduce((a, m) => a + m.tokens, 0);
        const n = Number(o["sample-n"] ?? 2000);
        const pick = stratifiedPick(metas, n);
        const samp = metas.filter(m => pick.has(m.n)).reduce((a, m) => a + m.tokens, 0);
        console.log(`${f}: full ${metas.length.toLocaleString()} cases, ${all.toLocaleString()} tok, $${usd(all).toFixed(2)}`);
        console.log(`${f}: stratified ${pick.size.toLocaleString()} cases, ${samp.toLocaleString()} tok, $${usd(samp).toFixed(2)}`);
        continue;
      }
      console.log(`== judge ${f} / ${judge}`);
      const r = await runJudge({
        feature: f, judge: judge as any,
        limit: o.limit ? Number(o.limit) : undefined,
        sample: o.sample === "stratified" ? "stratified" : undefined,
        sampleN: o["sample-n"] ? Number(o["sample-n"]) : undefined,
        yes: !!o.yes,
        timeoutMs: o["timeout-ms"] ? Number(o["timeout-ms"]) : undefined, // else PI_JEV_TIMEOUT_MS, default 15000
      });
      console.log(`   ran=${r.ran} resumed=${r.skipped} -> ${judgedPath(f, judge)}`);
    }
    return;
  }

  if (cmd === "score") {
    for (const f of FEATURES) {
      if (!existsSync(judgedPath(f, judge))) { console.log(`skip ${f}: no judged file for ${judge}`); continue; }
      const r = await runScore(f, judge);
      console.log("\n" + toMarkdown(r));
    }
    return;
  }

  if (cmd === "report") {
    const dir = join(OUT_ROOT, "scores");
    const files = existsSync(dir) ? readdirSync(dir).filter(f => f.endsWith(".json") && f !== "extract.json").sort() : [];
    const ex = existsSync(join(dir, "extract.json")) ? JSON.parse(readFileSync(join(dir, "extract.json"), "utf8")) : null;
    const out: string[] = [
      "# Tier 1 offline replay results",
      "",
      "Generated by `bun run bench/replay/cli.ts report`. Aggregates only; cases and judged",
      `probabilities stay under \`~/.pi/agent/pi-jev/replay/\` because they contain verbatim session text.`,
      "",
    ];
    if (ex) {
      out.push("## Corpus", "",
        `\`${ex.sessions}\` sessions > 50 KB, \`${ex.turns?.toLocaleString()}\` prompt turns, extracted in ${Math.round(ex.secs)}s.`, "",
        "| feature | cases | label balance | size |", "|---|---:|---|---:|",
        `| triage | ${ex.triage.cases.toLocaleString()} results / ${ex.triage.blocks.toLocaleString()} blocks | ${(100 * ex.triage.needed / (ex.triage.blocks || 1)).toFixed(1)}% needed | ${(ex.triage.resultBytes / 1e6).toFixed(0)} MB of results |`,
        "");
    }
    const scores = files.map(f => JSON.parse(readFileSync(join(dir, f), "utf8")));
    // Local (kev / JevK5) next to hosted Jev, the pair the run compares.
    const ORDER = ["local", "vercel", "typesafe", "mock"];
    const byJudge = (a: any, b: any) =>
      (ORDER.indexOf(a.judge) + 1 || 99) - (ORDER.indexOf(b.judge) + 1 || 99) || a.judge.localeCompare(b.judge);

    out.push("## Head to head", "",
      "Same 2,000-case stratified sample, one column per judge; the case ids are in",
      "`~/.pi/agent/pi-jev/replay/samples/triage.stratified-2000.ids`. `vercel` is hosted Jev",
      "(`typesafe-ai/jev` through Vercel AI Gateway); `local` is the kev-0.8b sidecar",
      "(`KEV_TEMPERATURE=1.3`);",
      "`mock` is the deterministic noise floor. A judge missing from the table has no score on the",
      "current sample.", "");
    for (const feat of FEATURES) {
      const fs = scores.filter(s => s.feature === feat).sort(byJudge);
      if (fs.length) out.push(comparisonTable(feat, fs), "");
    }

    out.push("## Scores", "");
    for (const feat of FEATURES) for (const s of scores.filter(x => x.feature === feat).sort(byJudge)) out.push(toMarkdown(s), "");

    out.push("## Jev cost", "", "`$0.042 / M` input tokens, output free. Estimated from case size at 4 chars/token.", "",
      "| feature | full cases | full tokens | full $ | 2,000-case stratified tokens | 2,000-case $ |", "|---|---:|---:|---:|---:|---:|");
    for (const f of FEATURES) {
      try {
        const metas = await scanCases(f);
        const all = metas.reduce((a, m) => a + m.tokens, 0);
        const pick = stratifiedPick(metas, 2000);
        const samp = metas.filter(m => pick.has(m.n)).reduce((a, m) => a + m.tokens, 0);
        out.push(`| ${f} | ${metas.length.toLocaleString()} | ${all.toLocaleString()} | $${usd(all).toFixed(2)} | ${samp.toLocaleString()} | $${usd(samp).toFixed(2)} |`);
      } catch { /* not extracted */ }
    }
    out.push("", "The billed `vercel` input tokens are in each score block's judge-cost line. Reproducing the",
      "`vercel` column (key loads from `~/.config/vercel/.env` via `extension/src/judge/dotenv.ts`):", "",
      "```sh",
      "export PI_JEV_BENCH_CONCURRENCY=2",
      "bun run bench/replay/cli.ts judge --judge vercel --sample stratified --limit 2000 --timeout-ms 30000",
      "bun run bench/replay/cli.ts score --judge vercel && bun run bench/replay/cli.ts report",
      "```", "",
      "Upstream sheds load with HTTP 429 (\"upstream provider is currently experiencing high demand\").",
      "`judge.ts` retries each case with exponential backoff (30 s start, 5 min cap) and trips a",
      "breaker (exit 3) when fewer than 50% of the last 50 attempts succeed. A case that never gets an",
      "answer is not written, so no fail-open answer reaches scoring; rerunning resumes the gaps.", "",
      "## Request shape", "",
      "Each case sends the extension's own request: `buildState` (task context in the extension's",
      "`taskContext` format, tool name, and the leading run of full-text blocks that fits the judge's",
      "state cap) and `buildQuestions` (one noul per judged block plus the error question). Blocks past",
      "the cap are unjudged and kept, as in the extension.",
      "",
      "Block splitting, the judge state, tool matching, the question set and the `decide()` policy are imported from",
      "`extension/src/triage/core.ts` — the bench keeps no copies, so replay cannot drift from what ships.",
      "",
      "## Reading the numbers", "",
      "- **Sampling.** Triage is scored on the same 2,000-case stratified sample for every judge, so",
      "  the columns are paired and differences are the ranker, not the sample. Strata are",
      "  needed/not-needed × result size.",
      "- **Triage cases were re-extracted** after `splitBlocks` gained a 1,500-char per-block cap",
      "  (`DEFAULT_BLOCK_CHARS`): 30,443 cases / 300,731 blocks, up from 27,110 / 235,283, because",
      "  long-line output now splits into more blocks and more results clear the minimum block count.",
      "  Earlier triage cases, judged files and scores are archived under",
      "  `~/.pi/agent/pi-jev/replay/archive-presplit/`; the kev `local` triage column needs a rerun on",
      "  the new sample and is absent until then.",
      "- `local` is kev-0.8b (or JevK5), `mock` the deterministic noise floor.",
      "- The error gate is the judge's own answer to the error question, as in the extension: P ≥ 0.5",
      "  (or no answer) keeps the whole result. There is no regex fallback.",
      `- **Triage question.** Every judge is asked the \`${process.env.PI_JEV_QUESTION_SET || "winnow"}\` set's block question`,
      "  from `extension/src/triage/core.ts` (`PI_JEV_QUESTION_SET`: `winnow` is winnow v0.5.0's `structured`",
      "  set, `sharpened` the \"…Answer no if it is from an unrelated file…\" phrasing). On the pre-split",
      "  sample the bare phrasing left kev at AUC 0.525.",
      "- Two views. The **threshold sweep** measures the ranker alone. The **shipped policy**",
      "  row runs the extension's real `decide()` — head and tail pinned, error gate,",
      "  20% minimum prune ratio — and is the number that predicts production.",
      "- Weak labels are recall-oriented: a block counts as needed if a later edit reuses one of its",
      "  distinctive lines, a later read opens a path it names, or the final answer quotes an identifier",
      "  from it. Blocks that only informed the model's reasoning are labelled not-needed, so regret is a",
      "  lower bound on real cost.",
      "- **Rerun pending.** Triage numbers produced before 2026-09-23 used a pre-`winnow` block question",
      "  and sent no `tool` in `state`; they are being rerun with the `winnow` set and `{ task, tool }`.", "");
    const path = join(HERE, "RESULTS.md");
    writeFileSync(path, out.join("\n"));
    console.log(`wrote ${path}`);
    return;
  }

  console.error("usage: bun run bench/replay/cli.ts <extract|judge|score|report> [--judge j] [--limit n] [--sample stratified] [--timeout-ms n] [--dry-run] [--yes]");
  process.exit(1);
}

main().catch(e => { console.error(String(e?.stack ?? e)); process.exit(1); });
