#!/usr/bin/env python3
"""Apply the guarded RTK bypass to a generated TokenJuice Pi extension."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

SUPPORTED_TOKENJUICE_VERSION = "0.8.5"

ORIGINAL = '''      const command = isRecord2(event.input) && typeof event.input.command === "string" ? event.input.command : "";
      if (!enabled || !autoCompactEnabled || !command) {
        return void 0;
      }
      const outputText = extractTextContent(event.content);
'''
PATCHED = '''      const command = isRecord2(event.input) && typeof event.input.command === "string" ? event.input.command : "";
      if (!enabled || !autoCompactEnabled || !command) {
        return void 0;
      }
      if (command.trim().startsWith("rtk ")) {
        return void 0;
      }
      const outputText = extractTextContent(event.content);
'''


def fail(message: str) -> "None":
    raise SystemExit(f"✗ {message}")


def default_extension_path() -> Path:
    agent_dir = Path(os.environ.get("PI_CODING_AGENT_DIR", Path.home() / ".pi" / "agent"))
    return agent_dir.expanduser() / "extensions" / "tokenjuice.js"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("path", nargs="?", type=Path, default=default_extension_path())
    parser.add_argument("--check", action="store_true", help="verify without modifying the extension")
    args = parser.parse_args()

    path = args.path.expanduser().resolve()
    if not path.is_file():
        fail(f"TokenJuice Pi extension missing: {path}")

    text = path.read_text()
    version_marker = f"generated by tokenjuice v{SUPPORTED_TOKENJUICE_VERSION}"
    if version_marker not in text:
        fail(f"unsupported TokenJuice Pi extension version (expected {SUPPORTED_TOKENJUICE_VERSION}): {path}")

    original_count = text.count(ORIGINAL)
    patched_count = text.count(PATCHED)
    if patched_count == 1 and original_count == 0:
        print(f"✓ verified TokenJuice {SUPPORTED_TOKENJUICE_VERSION} RTK bypass: {path}")
        return 0
    if patched_count != 0 or original_count != 1:
        fail(
            "unsupported TokenJuice Pi extension shape "
            f"(original={original_count}, patched={patched_count}): {path}"
        )
    if args.check:
        fail(f"RTK bypass is not applied: {path}")

    path.write_text(text.replace(ORIGINAL, PATCHED, 1))
    print(f"✓ applied TokenJuice {SUPPORTED_TOKENJUICE_VERSION} RTK bypass: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
