#!/usr/bin/env python3
"""Apply the guarded RTK bypass to a generated TokenJuice Pi extension."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

SUPPORTED_TOKENJUICE_VERSION = "0.8.5"

ORIGINAL = '''      const command = isRecord2(event.input) && typeof event.input.command === "string" ? event.input.command : "";
      if (!enabled || !autoCompactEnabled || !command) {
        return void 0;
      }
      const outputText = extractTextContent(event.content);
'''
PATCHED = '''      const command = isRecord2(event.input) && typeof event.input.command === "string" ? event.input.command : "";
      if (!enabled || !autoCompactEnabled || !command) {
        return void 0;
      }
      const wrapperInnerIndex = (argv) => {
        const wrapper = getCommandName(argv);
        if (["nohup", "command", "builtin", "exec", "noglob", "nocorrect"].includes(wrapper)) {
          return 1;
        }
        if (wrapper === "uv" && argv[1] === "run") {
          return 2;
        }
        let index = 1;
        if (wrapper === "timeout") {
          while (index < argv.length) {
            const arg = argv[index];
            if (["-s", "-k", "--signal", "--kill-after"].includes(arg)) {
              index += 2;
            } else if (["--preserve-status", "--foreground", "-v", "--verbose"].includes(arg) || /^-(?:s|k).+/u.test(arg) || /^--(?:signal|kill-after)=/u.test(arg)) {
              index += 1;
            } else if (arg === "--") {
              index += 1;
              break;
            } else {
              return index + 1;
            }
          }
          return -1;
        }
        if (wrapper === "nice" || wrapper === "time") {
          const valueOptions = wrapper === "nice" ? ["-n", "--adjustment"] : ["-f", "-o", "--format", "--output"];
          const flagOptions = wrapper === "nice" ? [] : ["-p", "-a", "-v", "--append", "--verbose", "--portability", "--quiet"];
          while (index < argv.length) {
            const arg = argv[index];
            if (valueOptions.includes(arg)) {
              index += 2;
            } else if (flagOptions.includes(arg) || wrapper === "nice" && (/^-\\d+$/u.test(arg) || /^-n.+/u.test(arg) || /^--adjustment=/u.test(arg)) || wrapper === "time" && (/^-[fo].+/u.test(arg) || /^--(?:format|output)=/u.test(arg))) {
              index += 1;
            } else if (arg === "--") {
              return index + 1;
            } else {
              return index;
            }
          }
        }
        return -1;
      };
      const argvRunsRtk = (initialArgv) => {
        let argv = initialArgv;
        for (let depth = 0; depth < 10; depth += 1) {
          if (getCommandName(argv) === "rtk") {
            return true;
          }
          const innerIndex = wrapperInnerIndex(argv);
          if (innerIndex < 1 || innerIndex >= argv.length) {
            return false;
          }
          argv = argv.slice(innerIndex);
        }
        return false;
      };
      const isRtkCommand = splitTopLevelCommandChain(command).some((chainSegment) => splitUnquotedPipes(chainSegment).some((pipelineSegment) => {
        const effectiveArgv = getEffectiveCommandArgv({ command: pipelineSegment });
        return argvRunsRtk(effectiveArgv.length > 0 ? effectiveArgv : tokenizeCommand(pipelineSegment));
      }));
      if (isRtkCommand) {
        return void 0;
      }
      const outputText = extractTextContent(event.content);
'''


def fail(message: str) -> "None":
    raise SystemExit(f"✗ {message}")


def default_extension_path() -> Path:
    agent_dir = Path(os.environ.get("PI_CODING_AGENT_DIR", Path.home() / ".pi" / "agent"))
    return agent_dir.expanduser() / "extensions" / "tokenjuice.js"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("path", nargs="?", type=Path, default=default_extension_path())
    parser.add_argument("--check", action="store_true", help="verify without modifying the extension")
    args = parser.parse_args()

    path = args.path.expanduser().resolve()
    if not path.is_file():
        fail(f"TokenJuice Pi extension missing: {path}")

    text = path.read_text()
    version_marker = f"generated by tokenjuice v{SUPPORTED_TOKENJUICE_VERSION}"
    if version_marker not in text:
        fail(f"unsupported TokenJuice Pi extension version (expected {SUPPORTED_TOKENJUICE_VERSION}): {path}")

    original_count = text.count(ORIGINAL)
    patched_count = text.count(PATCHED)
    if patched_count == 1 and original_count == 0:
        print(f"✓ verified TokenJuice {SUPPORTED_TOKENJUICE_VERSION} RTK bypass: {path}")
        return 0
    if patched_count != 0 or original_count != 1:
        fail(
            "unsupported TokenJuice Pi extension shape "
            f"(original={original_count}, patched={patched_count}): {path}"
        )
    if args.check:
        fail(f"RTK bypass is not applied: {path}")

    path.write_text(text.replace(ORIGINAL, PATCHED, 1))
    print(f"✓ applied TokenJuice {SUPPORTED_TOKENJUICE_VERSION} RTK bypass: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
