import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tokenjuiceCli = path.join(root, "node_modules", "tokenjuice", "dist", "cli", "main.js");
const patcher = path.join(root, "scripts", "apply-rtk-bypass.py");

function run(command, args, env) {
  const result = spawnSync(command, args, { encoding: "utf8", env });
  assert.equal(result.status, 0, `${command} failed:\n${result.stdout}\n${result.stderr}`);
  return result;
}

function event(command) {
  const output = Array.from(
    { length: 100 },
    (_, index) => `diagnostic line ${index}: ${"detail ".repeat(8)}`,
  ).join("\n");

  return {
    toolName: "bash",
    input: { command },
    content: [{ type: "text", text: output }],
    details: {},
    isError: false,
  };
}

test("generated TokenJuice bypasses RTK and compacts fallback output", async () => {
  const home = mkdtempSync(path.join(tmpdir(), "tokenjuice-rtk-"));
  const agentDir = path.join(home, ".pi", "agent");
  const extension = path.join(agentDir, "extensions", "tokenjuice.js");
  const originalHome = process.env.HOME;
  const originalAgentDir = process.env.PI_CODING_AGENT_DIR;
  const originalStats = process.env.TOKENJUICE_STATS;
  const env = {
    ...process.env,
    HOME: home,
    PI_CODING_AGENT_DIR: agentDir,
    TOKENJUICE_STATS: "off",
  };

  try {
    run(process.execPath, [tokenjuiceCli, "install", "pi"], env);
    assert.match(readFileSync(extension, "utf8"), /generated by tokenjuice v0\.8\.5/);

    run("python3", [patcher, extension], env);
    run("python3", [patcher, "--check", extension], env);

    process.env.HOME = home;
    process.env.PI_CODING_AGENT_DIR = agentDir;
    process.env.TOKENJUICE_STATS = "off";
    writeFileSync(path.join(agentDir, "package.json"), '{"type":"module"}\n');

    const { default: registerTokenjuice } = await import(`${pathToFileURL(extension).href}?verify=${Date.now()}`);
    const handlers = new Map();
    registerTokenjuice({
      on(name, handler) {
        handlers.set(name, handler);
      },
      registerCommand() {},
      appendEntry() {},
    });

    const ctx = {
      cwd: home,
      hasUI: false,
      sessionManager: {
        getHeader: () => ({ cwd: home }),
        getCwd: () => home,
        getEntries: () => [],
        getBranch: () => [],
      },
      ui: { notify() {} },
    };
    await handlers.get("session_start")?.({}, ctx);

    assert.equal(await handlers.get("tool_result")(event("rtk git status"), ctx), undefined);

    const compacted = await handlers.get("tool_result")(event("custom-verbose-command"), ctx);
    assert.ok(compacted);
    assert.match(compacted.content[0].text, /tokenjuice compacted bash output/);
    assert.equal(compacted.details.tokenjuice.compacted, true);
  } finally {
    if (originalHome === undefined) delete process.env.HOME;
    else process.env.HOME = originalHome;
    if (originalAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR;
    else process.env.PI_CODING_AGENT_DIR = originalAgentDir;
    if (originalStats === undefined) delete process.env.TOKENJUICE_STATS;
    else process.env.TOKENJUICE_STATS = originalStats;
    rmSync(home, { recursive: true, force: true });
  }
});
